services:
  tasks-in:
    image: rabbitmq:3-management-alpine
    container_name: broker
    ports:
      - 5672:5672   # for sender and consumer connections
      - 15672:15672 # for serve RabbitMQ GUI
    # environment:
      # - RABBITMQ_DEFAULT_PASS=user
      # - RABBITMQ_DEFAULT_USER=password
    # volumes:
    #   - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
    #   - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    restart: always
    # networks:
    #   - app-network